version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: cardcataloger-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: CardCataloger
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cardcataloger-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Ollama AI Service with GPU Support
  ollama:
    image: ollama/ollama:latest
    container_name: cardcataloger-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - cardcataloger-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cardcataloger-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mongodb://mongodb:27017/CardCataloger
      - OLLAMA_BASE_URL=http://ollama:11434
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_change_in_production}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET:-default_refresh_secret_change_in_production}
      - EBAY_APP_ID=${EBAY_APP_ID}
      - EBAY_CERT_ID=${EBAY_CERT_ID}
      - EBAY_DEV_ID=${EBAY_DEV_ID}
      - EBAY_USER_TOKEN=${EBAY_USER_TOKEN}
      - EBAY_SANDBOX=${EBAY_SANDBOX:-true}
    volumes:
      - ./card-images:/app/card-images:ro
      - ./uploads:/app/uploads
      - backend_logs:/app/logs
    networks:
      - cardcataloger-network
    depends_on:
      - mongodb
      - ollama
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend Web Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cardcataloger-frontend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - cardcataloger-network
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  cardcataloger-network:
    driver: bridge
    name: cardcataloger-network

volumes:
  mongodb_data:
    name: cardcataloger-mongodb-data
  ollama_data:
    name: cardcataloger-ollama-data
  backend_logs:
    name: cardcataloger-backend-logs