# Development overrides
version: '3.8'

# Development overrides - only used when explicitly specified
# This file is automatically loaded by docker-compose
# To use production mode, run: docker-compose -f docker-compose.yml up -d

services:
  # Development overrides for backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./server:/app:cached
      - /app/node_modules
      - ./card-images:/app/card-images:ro
    command: ["npm", "run", "dev"]

  # Development overrides for frontend  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "8000:5173"  # Also expose on port 8000 for consistency
    volumes:
      - ./client:/app:cached
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000

  # Development database with local volume
  mongodb:
    volumes:
      - ./data/mongodb:/data/db