# Development-specific configurations for Docker services
services:
  # Backend development configuration
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./card-images:/app/card-images:ro
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/CardCataloger?authSource=admin
      - OLLAMA_BASE_URL=http://ollama:11434
      - DOCKER_CONTAINER=true
    command: npm run dev

  # Frontend development configuration  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - vite_cache:/tmp/vite-cache
    environment:
      - NODE_ENV=development
      - VITE_CACHE_DIR=/tmp/vite-cache
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"

  # MongoDB development configuration
  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db

volumes:
  mongodb_dev_data:
    driver: local
  vite_cache:
    driver: local