# Development overrides

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app:cached
      - /app/node_modules
      - ./card_images:/app/card_images:ro
    environment:
      - NODE_ENV=development
      - DOCKER_CONTAINER=true

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:cached
      - /app/node_modules
      - vite_cache:/tmp/vite-cache
    environment:
      - NODE_ENV=development

  mongodb:
    volumes:
      - mongodb_dev_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_dev_data:
    name: cardcataloger_mongodb_dev_data
  vite_cache:
    name: cardcataloger_vite_cache