# Development overrides - Frontend intentionally excluded to use production build

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app:cached
      - /app/node_modules
      - ./card_images:/app/card_images:ro
    environment:
      - NODE_ENV=development
      - DOCKER_CONTAINER=true

  mongodb:
    volumes:
      - mongodb_dev_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_dev_data:
    driver: local